# Generated by Django 4.2.2 on 2023-12-18 13:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('categorizer', '0004_alter_categorizedtransaction_transaction'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categorizedtransaction',
            name='transaction',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='categorized_transactions', to='categorizer.transaction'),
        ),
    ]
