# Generated by Django 3.2.23 on 2023-12-28 11:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('categorizer', '0006_alter_categorizedtransaction_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='categorizedtransaction',
            name='pattern',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='categorized_transactions', to='categorizer.categorypattern'),
        ),
    ]
